package com.smartwificonnect.data.local

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Encrypts/decrypts Wi-Fi passwords using AES-256/GCM backed by Android Keystore.
 * The key never leaves the secure hardware — no plaintext key material is stored in app storage.
 *
 * Format stored in DB: enc:v1:Base64( IV[12 bytes] + ciphertext )
 *
 * Backward-compatible: old plaintext rows are returned unchanged. Old unprefixed encrypted rows
 * are still decoded, but failed GCM decrypt returns an empty value instead of exposing ciphertext.
 */
internal object PasswordCipher {

    private const val ENCRYPTED_PREFIX = "enc:v1:"
    private const val KEY_ALIAS = "swc_pw_aes_key_v1"
    private const val ANDROID_KEYSTORE = "AndroidKeyStore"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_BITS = 128
    private const val GCM_IV_BYTES = 12

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        val existing = ks.getKey(KEY_ALIAS, null)
        if (existing != null) return existing as SecretKey

        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setUserAuthenticationRequired(false)
            .build()

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            .apply { init(spec) }
            .generateKey()
    }

    fun encrypt(plaintext: String): String {
        if (plaintext.isEmpty()) return ""
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv                                      // 12 bytes, generated by KeyStore
        val encrypted = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))
        val combined = ByteArray(GCM_IV_BYTES + encrypted.size)
        System.arraycopy(iv, 0, combined, 0, GCM_IV_BYTES)
        System.arraycopy(encrypted, 0, combined, GCM_IV_BYTES, encrypted.size)
        return ENCRYPTED_PREFIX + Base64.encodeToString(combined, Base64.NO_WRAP)
    }

    fun decrypt(ciphertext: String): String {
        if (ciphertext.isEmpty()) return ""
        val hasEncryptedPrefix = ciphertext.startsWith(ENCRYPTED_PREFIX)
        val storedValue = if (hasEncryptedPrefix) {
            ciphertext.removePrefix(ENCRYPTED_PREFIX)
        } else {
            ciphertext
        }
        return try {
            val combined = Base64.decode(storedValue, Base64.NO_WRAP)
            if (combined.size <= GCM_IV_BYTES) {
                return if (hasEncryptedPrefix) "" else ciphertext
            }
            val iv = combined.copyOfRange(0, GCM_IV_BYTES)
            val encrypted = combined.copyOfRange(GCM_IV_BYTES, combined.size)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
            String(cipher.doFinal(encrypted), Charsets.UTF_8)
        } catch (_: Exception) {
            if (hasEncryptedPrefix || looksLikeLegacyCiphertext(storedValue)) "" else ciphertext
        }
    }

    private fun looksLikeLegacyCiphertext(value: String): Boolean {
        if (value.length < 40 || value.length % 4 != 0) return false
        if (!Regex("^[A-Za-z0-9+/]+={0,2}$").matches(value)) return false
        return runCatching {
            Base64.decode(value, Base64.NO_WRAP).size > GCM_IV_BYTES
        }.getOrDefault(false)
    }
}
